Excluding Vendor Directories in config.yml
Per https://jekyllrb.com/docs/troubleshooting/, I was getting a build error:

```
 ERROR: YOUR SITE COULD NOT BE BUILT:
    ------------------------------------
    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>':
    Document 'vendor/bundle/gems/jekyll-3.4.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb'
    does not have a valid date in front matter.
```

updated the `_config.yml` file per :point_up: to hopefully fix this issue.